# These are all available as ENV['NAME'] eg. ENV['DEV_NAME'] returns DEV_NAME

# Where is the server hosted
BASE_URL: ...

# GitHub info
GITHUB_NAME: ...
GITHUB_REPO: ...
GITHUB_AUTH: ... # You'll need to generate your own on GitHub

# Mailer info
GMAIL_USERNAME: ...
GMAIL_PASSWORD: ...

# Admin info
ADMIN_NAME: ...
ADMIN_EMAIL: ...
ADMIN_PASSWORD: ...

# Developer name (GitHub)
DEV_NAME: ...
DEV_MAIL: ...

# Database info
DATABASE_USER: badger
DATABASE_PASS: ...

# Roles for users and suppliers
ROLES: [admin, manager, technician, user, guest]
SUPPLIERS: [] #All the suppliers

# The main company info
COMPANY: ''
